### PR TITLE
Fix bug in tape order during simplify

### LINKED ISSUE #815: [BUG] Cannot compile training graph
**Describe the bug**
I cannot compile my training graph. I have followed the documentation on [this](https://ml-explore.github.io/mlx/build/html/usage/compile.html) page to compile the graph. Since I have dropout, I have additionally included `mx.random.state` in my `state` variable. However, when I try to run my code I get the following error:

```
    loss = step(x, y)
           ^^^^^^^^^^
IndexError: unordered_map::at: key not found
```

Any help or guidance on this issue would be much appreciated. I may be doing something wrong here.

**To Reproduce**

Clone my repo https://github.com/georgeherbert/gpt-mlx/ and run `train.py`.

**Expected behavior**

The training graph to compile and training to commence.

**Desktop (please complete the following information):**
 - OS Version: MacOS 14.2.1
 - Version: 0.6.0

### PR DESCRIPTION
**Pull request by awni**
## Proposed changes

Closes #815

### CODE REVIEW

File: mlx/compile.cpp [hunk 1]
```diff
@@ -415,6 +415,11 @@ void compile_simplify(
   }
   tape = std::move(new_tape);
 
+  std::map<std::uintptr_t, uint32_t> tape_order;
```
Comment (angeloskath) [inline mlx/compile.cpp:418]: Out of curiosity why a `map` instead of an `unordered_map`?

**Review by angeloskath — APPROVED** [review]
Looks really good! I can't imagine the nightmare to track these down...

File: mlx/compile.cpp (hunk 1 above)
Comment (awni) [reply mlx/compile.cpp:418]: Typo!
