### PR TITLE
Fixes segfault when compiling checkpointed functions

### LINKED ISSUE #1162: [BUG] compile + checkpoint segfaults
```python
import mlx.core as mx
import mlx.nn as nn
from mlx.nn.utils import checkpoint

dims = 32

class Linear(nn.Module):
    def __init__(self, dims):
        super().__init__()
        self.proj = nn.Linear(dims, dims)

    def __call__(self, x):
        l = checkpoint(self.proj) 
        x = l(x)
        return x

model = Linear(dims)
mx.eval(model.parameters())

@mx.compile
def step(inputs):
    return model(inputs)

inputs = mx.ones((2, dims), dtype=mx.float32)
mx.eval(inputs)

out = step(inputs)
mx.eval(out)
```

Above segfaults with checkpointing but not without.

### PR DESCRIPTION
**Pull request by angeloskath**
Closes #1162.

See title. It exposes a `clear_compiler_cache` method in C++ and Python which is also registered `atexit`.

### CODE REVIEW

File: python/src/transforms.cpp [hunk 1]
```diff
@@ -961,12 +960,22 @@ void init_transforms(nb::module_& m) {
         Globally enable compilation. This will override the environment
         variable ``MLX_DISABLE_COMPILE`` if set.
       )pbdoc");
+  m.def(
+      "clear_compiler_cache",
+      &clear_compiler_cache,
+      R"pbdoc(
+        Clear the compiler cache causing all compiled function to recompile if
+        they are called again.
+      )pbdoc");
```
Comment (awni) [inline python/src/transforms.cpp:969]: Do we need a binding for that / what is the intended use for it?

File: mlx/compile.cpp [hunk 2]
```diff
@@ -266,6 +266,10 @@ class CompilerCache {
     cache_.erase(fun_id);
   }
 
+  std::unordered_map<std::uintptr_t, std::vector<CacheEntry>>& entries() {
+    return cache_;
+  }
```
Comment (awni) [inline mlx/compile.cpp:271]: Do you think it makes sense to make this a `clear` function instead?

**Review by awni — APPROVED** [review]
Awesome! Thanks for the fix! Left a couple minor comments re the API. But I'm good to merge this as is.

File: python/src/transforms.cpp (hunk 1 above)
Comment (angeloskath) [reply python/src/transforms.cpp:969]: I 'll remove it. I added it for testing and then thought that maybe someone wanted to clean things up for long running programs.

File: mlx/compile.cpp (hunk 2 above)
Comment (angeloskath) [reply mlx/compile.cpp:271]: Same as above initially added because I had more functionality for testing and didn't limit enough the API in detail. Will change it to clear.

**Comment by angeloskath** [comment]
@awni let me know if this is better. I put the clear in `detail::` and changed the name to `detail::compile_clear_cache()`.

**Comment by awni** [comment]
Looks perfect!
