### PR TITLE
[CUDA] Exit on crash and more helpful errors

### LINKED ISSUE #2821: [BUG] [CUDA] Hangs on OOM crash with unhelpful error message
On B200 the following crashes and then hangs.

```python
import mlx.core as mx
arrs = []
while True:
    a = mx.random.normal(shape=(4096, 4096))
    mx.eval(a)
    print(mx.get_peak_memory() / 1e9)
    arrs.append(a)
```

```
RuntimeError: cudaMallocManaged failed: an illegal memory access was encountered.
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFreeAsync(buf->data, free_streams_[buf->device]) failed: an illegal memory access was encountered
```

It shouldn't hang and it should give a more useful error message.

Also, I'm wondering also what the behavior we want is.. should it be a hard crash when it runs out of device memory or should it fall back to managed memory which could use CPU RAM as well?

### PR DESCRIPTION
**Pull request by awni**
- Check error state after `event.wait` to catch errors during kernel execution
- Fix OOM error messaging by properly returning nullptr when alloc fails
- Don't throw in scheduler destructor
- Don't destroy cuda resources when error state is set

Closes #2821

### CODE REVIEW

File: mlx/backend/cuda/allocator.cpp [hunk 1]
```diff
@@ -154,17 +154,21 @@ CudaAllocator::malloc_async(size_t size, int device, cudaStream_t stream) {
     }
     lock.unlock();
     if (!buf) {
-      buf = new CudaBuffer{nullptr, size, device};
       cudaError_t err;
+      void* data;
```
Comment (zcbenz) [inline mlx/backend/cuda/allocator.cpp]:
```suggestion
      void* data = nullptr;
```

File: mlx/backend/cuda/cuda_utils.h [hunk 2]
```diff
@@ -29,6 +29,9 @@ class CudaHandle {
   }
 
   ~CudaHandle() {
+    if (cudaPeekAtLastError() != cudaSuccess) {
```
Comment (zcbenz) [inline mlx/backend/cuda/cuda_utils.h:33]: Can you add a comment on the reason of the check?

**Review by zcbenz — APPROVED** [review]
Nice!
