### PR TITLE
Metal validation

### LINKED ISSUE #410: [BUG] with metal API validation turned on Gather::eval_gpu causes aborts when trying to allocate 0 sized buffer
**Describe the bug**

With metal API validation turned on (`METAL_DEVICE_WRAPPER_TYPE=1 METAL_DEBUG_ERROR_MODE=0`) if you call `Gather::eval_gpu()` for an array that has a zero dimension input you will get an assertion failure and abort:

```
-[MTLDebugDevice newBufferWithLength:options:]:646: failed assertion `Buffer Validation
Cannot create buffer of zero length.
```

Specifically these lines:

```
  // Allocate and fill buffers for shapes and strides
  int idx_ndim = nidx ? inputs[1].ndim() : 0;
  auto idx_shapes_buf = allocator::malloc_or_wait(sizeof(int) * idx_ndim);
  auto idx_strides_buf = allocator::malloc_or_wait(sizeof(size_t) * idx_ndim);
```

`inputs[1]` might be a 0 dimension scalar array (e.g. `mx.array(1)`) in which case `ndim()` is 0 (and honestly the `: 0` default looks a little iffy as it will cause the same trouble).  Anyway, the call to `allocator::malloc_or_wait()` with a size of 0 triggers the abort when metal API validation is turned on.

**To Reproduce**

```python
import mlx.core as mx

arr = mx.array([2, 4, 6, 8]).reshape((2, 2))
x = mx.take(arr, mx.array(1), 0)
print(x)
```

run as:

```
METAL_DEVICE_WRAPPER_TYPE=1 METAL_DEBUG_ERROR_MODE=0 python test.py
```

**Expected behavior**

This should not abort().

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.1]
 - Commit hash: `753867123d36c13b29637c648068fd83844b0498`

### PR DESCRIPTION
**Pull request by awni**
## Proposed changes

- C++ tests run clean with Metal validation enabled.
- Add C++ tests with Metal validation to MacOS CircleCI

Closes #410

### CODE REVIEW

**Comment by awni** [comment]
CC @davidkoski

File: mlx/backend/metal/indexing.cpp [hunk 1]
```diff
@@ -1,7 +1,7 @@
 // Copyright © 2023 Apple Inc.
-
 #include <algorithm>
 #include <cassert>
+#include <iostream> // TODO
```
Comment (jagrit06) [inline mlx/backend/metal/indexing.cpp:4]: I know this has a TODO, just wanted to point it out before a merge

Comment (awni) [reply mlx/backend/metal/indexing.cpp:4]: Ty! I knew that TODO was a good idea :)
