### PR TITLE
Fix reshaping of empty arrays

### LINKED ISSUE #789: should not be able to reshape a zero size array
**Describe the bug**

```
>>> a = mx.zeros([1, 0, 32, 64])
>>> a.shape
(1, 0, 32, 64)
>>> a.reshape(1, 0, -1).shape
(1, 0, -1)
```

We should not end up with a -1 in any dimension -- we probably shouldn't be able to reshape a zero size array.  Numpy reports:

```
>>> b.reshape(1, 0, -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot reshape array of size 0 into shape (1,0,newaxis)
```

for a similar case.

**To Reproduce**

See above.

**Expected behavior**

Probably an error thrown.

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 14.1.2]
 - Version [e.g. 0.7.0] 0.5.0

**Additional context**

### PR DESCRIPTION
**Pull request by angeloskath**
Simply fixes #789 .

```python
import mlx.core as mx
import numpy as np

x = mx.random.normal((100, 0, 1024))
y = np.random.randn(100, 0, 1024)

x.reshape(2, 50, 0).shape  # (2, 50, 0)
y.reshape(2, 50, 0).shape  # (2, 50, 0)

x.reshape(2, 50, -1).shape  # (2, 50, 0)
y.reshape(2, 50, -1).shape  # (2, 50, 0)

x.reshape(2, 50, 0, -1).shape  # throws ValueError: Cannot infer the shape of an empty array
y.reshape(2, 50, 0, -1).shape  # throws ValueError: cannot reshape array of size 0 into shape (2,50,0,newaxis)
```

### CODE REVIEW

File: mlx/ops.cpp [hunk 1]
```diff
@@ -300,19 +300,27 @@ array reshape(
...
+  // Infer the shape
   if (size > 0) {
     auto q_and_r = std::ldiv(a.size(), size);
     if (infer_idx >= 0) {
       shape[infer_idx] = q_and_r.quot;
       size *= q_and_r.quot;
     }
+  } else if (infer_idx >= 0) {
+    std::ostringstream msg;
+    throw std::invalid_argument("Cannot infer the shape of an empty array");
```
Comment (awni) [inline mlx/ops.cpp:313]: Nitty nit:

```suggestion
    throw std::invalid_argument("[reshape] Cannot infer the shape of an empty array");
```

**Review by awni — APPROVED** [review]
Thanks for the fix!!

File: mlx/ops.cpp (hunk 1 above)
Comment (angeloskath) [reply mlx/ops.cpp:313]: Yeah and also forgot the `ostringstream`. Let me fix all these...
