### PR TITLE
Fix `mx.core.linspace` type annotation

### LINKED ISSUE #2801: Partially unknown type for mlx.core.linspace with basedpyright.
**Describe the bug**

Running `basedpyright` on the code below results in the following type warning:

```sh
❯ uvx -w mlx basedpyright mlx_run.py
  mlx_run.py:1:22 - information: Type of "linspace" is partially unknown
  Type of "linspace" is "(start: Unknown, stop: Unknown, num: int | 
    None = 50, dtype: Dtype | None = float32, stream: Stream | Device | 
    None = None) -> array" (reportUnknownVariableType)
```

**To Reproduce**

Save this as `mlx_run.py`:

```python
from mlx.core import linspace, pi
theta = linspace(0, 2 * pi, 100)  # elec angle (rad)
```

Run `basedpyright`:

```sh
uvx -w mlx basedpyright mlx_run.py
```

**Expected behavior**
No type error.

**Desktop**
 - OS Version: macOS 26.1
 - mlx Version: 0.30.0

### PR DESCRIPTION
**Pull request by CC-Yeh**
## Proposed changes

Close #2801 

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

File: python/src/ops.cpp [hunk 1]
```diff
@@ -1445,7 +1445,7 @@ void init_ops(nb::module_& m) {
       "dtype"_a.none() = mx::float32,
       "stream"_a = nb::none(),
       nb::sig(
-          "def linspace(start, stop, num: Optional[int] = 50, dtype: Optional[Dtype] = float32, stream: Union[None, Stream, Device] = None) -> array"),
+          "def linspace(start: Union[int, float], stop: Union[int, float], num: Optional[int] = 50, dtype: Optional[Dtype] = float32, stream: Union[None, Stream, Device] = None) -> array"),
```
Comment (awni) [inline python/src/ops.cpp]:
```suggestion
          "def linspace(start: scalar, stop: scalar, num: Optional[int] = 50, dtype: Optional[Dtype] = float32, stream: Union[None, Stream, Device] = None) -> array"),
```

Comment (CC-Yeh) [reply python/src/ops.cpp]: Thanks! It's much neater.

Comment (CC-Yeh) [reply python/src/ops.cpp]: Defined here: https://github.com/ml-explore/mlx/blob/main/python/mlx/_stub_patterns.txt

**Comment by CC-Yeh** [comment]
@awni

Looks like a sporadic failure, can you trigger the test again?
