### PR TITLE
Segmented mm nax kernel

### LINKED ISSUE #3362: [Bug] MoE LoRA training crashes on M5 Max — missing float32 NAX gather_mm kernel
## Bug

LoRA training of MoE models (Qwen3.5-35B-A3B) on Apple M5 Max crashes with:

```
RuntimeError: [metal::Device] Unable to load function steel_gather_mm_rhs_nax_nt_float32_float32_bm16_bn128_bk128_wm1_wn4
Function steel_gather_mm_rhs_nax_nt_float32_float32_bm16_bn128_bk128_wm1_wn4 was not found in the library
```

## Root Cause

`mlx/backend/metal/kernels/steel/gemm/kernels/steel_gemm_gather_nax.metal` only instantiates `gather_mm_rhs_nax` for `float16` and `bfloat16`:

```metal
instantiate_gather_mm_shapes_helper(float16, half, float16, half);
instantiate_gather_mm_shapes_helper(bfloat16, bfloat, bfloat16, bfloat);
```

**No float32 instantiation exists.** When TF32 is enabled (default on M5), `GatherMM::eval_gpu` routes float32 ops to the NAX path because `enable_tf32()` returns true. The NAX gather_mm kernel doesn't have a float32 variant, causing the crash.

## Workaround

```bash
export MLX_ENABLE_TF32=0
```

This routes float32 operations to the standard (non-NAX) gather_mm path which works.

## Proper Fix

Add float32 instantiation to `steel_gemm_gather_nax.metal`:

```metal
instantiate_gather_mm_shapes_helper(float32, float, float32, float);
```

Or, the dispatch logic in `matmul.cpp` should exclude float32 from the NAX path when the kernel isn't available.

## Reproduction

```bash
pip install mlx==0.31.1 mlx-lm==0.31.1
python -m mlx_lm lora \
  --model mlx-community/Qwen3.5-35B-A3B-4bit \
  --data ./data --train --batch-size 1 --iters 10
# Crashes immediately
```

With workaround:
```bash
MLX_ENABLE_TF32=0 python -m mlx_lm lora \
  --model mlx-community/Qwen3.5-35B-A3B-4bit \
  --data ./data --train --batch-size 1 --iters 10
# Works: 235 tok/s, val loss 0.522
```

## Environment

- MLX 0.31.1
- macOS 26, Apple M5 Max 128GB, Metal 4
- Model: Qwen3.5-35B-A3B-4bit (MoE, 256 experts)

### PR DESCRIPTION
**Pull request by angeloskath**
As the title suggests it adds a NAX kernel for the `segmented_mm`.  It also fixes #3362.

Micro benchmark numbers

```
float32
--------

| Case                | MLX before | MLX after | Speedup |
|---------------------|------------|-----------|---------|
| 2048x2048x4096x10   |      2.609 |     1.538 |   1.70x |
| 2048x2048x4096x50   |      3.163 |     2.266 |   1.40x |
| 2048x2048x4096x100  |      5.861 |     5.111 |   1.15x |
| 2048x2048x4096x200  |     10.697 |     9.710 |   1.10x |
| 2048x2048x8192x10   |      4.947 |     2.019 |   2.45x |
| 2048x2048x8192x50   |      5.526 |     3.233 |   1.71x |
| 2048x2048x8192x100  |      6.084 |     4.254 |   1.43x |
| 2048x2048x8192x200  |      9.129 |     7.942 |   1.15x |
| 4096x4096x16384x10  |     37.024 |    13.469 |   2.75x |
| 4096x4096x16384x50  |     37.826 |    20.329 |   1.86x |
| 4096x4096x16384x100 |     41.548 |    23.822 |   1.74x |
| 4096x4096x16384x200 |     49.209 |    31.521 |   1.56x |


float16
--------

| Case                | MLX before | MLX after | Speedup |
|---------------------|------------|-----------|---------|
| 2048x2048x4096x10   |      2.479 |     1.657 |   1.50x |
| 2048x2048x4096x50   |      2.620 |     1.312 |   2.00x |
| 2048x2048x4096x100  |      3.120 |     2.229 |   1.40x |
| 2048x2048x4096x200  |      5.638 |     4.832 |   1.17x |
| 2048x2048x8192x10   |      4.687 |     1.680 |   2.79x |
| 2048x2048x8192x50   |      4.776 |     1.855 |   2.57x |
| 2048x2048x8192x100  |      5.104 |     2.943 |   1.73x |
| 2048x2048x8192x200  |      6.075 |     4.283 |   1.42x |
| 4096x4096x16384x10  |     35.108 |     9.488 |   3.70x |
| 4096x4096x16384x50  |     36.647 |    11.823 |   3.10x |
| 4096x4096x16384x100 |     36.862 |    16.417 |   2.25x |
| 4096x4096x16384x200 |     39.391 |    15.950 |   2.47x |
```

### CODE REVIEW

File: mlx/backend/metal/matmul.cpp [hunk 1]
```diff
@@ -2478,15 +2478,36 @@ void segmented_mm(
...
+  };
+
   std::string base_name;
   base_name.reserve(128);
+  base_name += "steel_segmented_mm_";
+
+  // Use NAX kernel if available
+  if (use_nax) {
+    int average_k = K / batch_size_out;
+    bm = 64;
```
Comment (nastya236) [inline mlx/backend/metal/matmul.cpp:2500]: Just out of curiosity, why 2 x 2 simdgroups and 64 x 64 tiles?

File: mlx/backend/metal/matmul.cpp [hunk 2]
```diff
@@ -2557,8 +2584,9 @@ void segmented_mm(
 
   // Prepare the grid
   MTL::Size group_dims = MTL::Size(32, wn, wm);
-  MTL::Size grid_dims =
-      MTL::Size(params.tiles_n, params.tiles_m, batch_size_out);
+  MTL::Size grid_dims = (use_nax && bk == 64)
```
Comment (nastya236) [inline mlx/backend/metal/matmul.cpp:2587]: I am wondering should non nax kernel also swap dimensions when there are many small segments?

**Review by nastya236 — APPROVED** [review]
Looks great! I asked couple of questions as usual for my own understanding :)

File: mlx/backend/metal/matmul.cpp (hunk 1 above)
Comment (angeloskath) [reply mlx/backend/metal/matmul.cpp:2500]: Well this can be tuned for sure. I haven't actually ran extensive testing and it seemed like a good default 🤷‍♂️

File: mlx/backend/metal/matmul.cpp (hunk 2 above)
Comment (angeloskath) [reply mlx/backend/metal/matmul.cpp:2587]: Yeah it is possible. The idea was that we launch threadgroups in order x, y, z and since K is very small in these cases we want the different Ks to run one after the other since it is very likely that the 2nd matmul's K will be in the cache already.
